# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend

on:
  push:
    branches: [ master ]
    paths: "app/Karma/**"
  pull_request:
    branches: # == run tests only on pull request opens/updates to: ==
      - master
      - dev # dev
    paths:
      - "app/Karma/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout GitHub repo
        uses: actions/checkout@v2

      - name: set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        working-directory: ./app/Karma
        run: npm ci

      - name: run ESLint
        working-directory: ./app/Karma
        run: npx eslint ./
